name: "Feature Request"
description: Propose a new feature or meaningful improvement to OAK.
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        **Before submitting**, please check that no existing issue covers this request
        ([search here](https://github.com/goondocks-co/open-agent-kit/issues?q=is%3Aissue+label%3Aenhancement)).

  - type: dropdown
    id: category
    attributes:
      label: Feature category
      description: What kind of change is this?
      options:
        - New capability (something OAK cannot do today)
        - Enhancement to existing feature
        - Developer experience / ergonomics
        - Performance improvement
        - Accessibility / usability
    validations:
      required: true

  - type: checkboxes
    id: area
    attributes:
      label: Area(s) affected
      description: Select all that apply.
      options:
        - label: Installers and setup flow (install.sh / install.ps1 / pipx / uv / pip)
        - label: CLI commands and pipeline
        - label: Codebase Intelligence (daemon, activity, memory, search)
        - label: Agent integrations (hooks, MCP, skills)
        - label: Templates and rules management
        - label: Strategic planning / RFC workflow
        - label: Release, upgrade, and CI workflows
        - label: Documentation and developer experience
        - label: Other (describe below)
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem or motivation
      description: What pain point or gap does this address? Be specific about the current friction.
      placeholder: |
        Today, when I try to ...
        I have to ... which causes ...
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed solution
      description: Describe the desired behavior, UX, and any CLI/API surface changes.
      placeholder: |
        The feature would work as follows:
        1. User runs `oak ...`
        2. OAK responds with ...
    validations:
      required: true

  - type: dropdown
    id: breaking_change
    attributes:
      label: Could this be a breaking change?
      description: Would this change existing behavior, CLI flags, config format, or public API?
      options:
        - "No"
        - "Possibly — needs investigation"
        - "Yes — describe migration path in Additional context"
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: Expected scope
      options:
        - Small (single file or component)
        - Medium (cross-component, single feature)
        - Large (architecture-impacting, multiple features)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: How important is this to you?
      options:
        - Nice to have — no workaround needed
        - Moderate — I have a workaround but it's painful
        - High — this is blocking a key workflow
        - Critical — cannot use OAK effectively without this
    validations:
      required: true

  - type: dropdown
    id: willing_to_contribute
    attributes:
      label: Would you be willing to submit a PR for this?
      options:
        - "Yes — I can implement this"
        - "Yes — with guidance"
        - "No — but happy to test"
        - "No"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other approaches you thought about and why the proposed solution is preferable.

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Mockups, references, links, or anything else that helps.
